@hostname = localhost
@port = 9999
@host = {{hostname}}:{{port}}

@URI = http://{{hostname}}:{{port}}/v1

@birdid = 2

# GET all birds
GET {{URI}}/objects/bird/ HTTP/1.1
content-type: application/json

###

# GET all birds that are blue
GET {{URI}}/objects/bird/?color=blue&height=8 HTTP/1.1
content-type: application/json

###

# GET a bird
GET {{URI}}/objects/bird/{{birdid}} HTTP/1.1
content-type: application/json

###

# => SHOULD FAIl
# DELETE all bird 
DELETE {{URI}}/objects/bird/ HTTP/1.1
content-type: application/json

###

# DELETE a bird
DELETE {{URI}}/objects/bird/{{birdid}} HTTP/1.1
content-type: application/json

###

# CREATE a bird
POST {{URI}}/objects/bird HTTP/1.1
content-type: application/json

{
"attrs": {
    "color": "blue",
    "specie": "aigle",
    "height": 105,
    "owner": 1
}
}

###

# CREATE => with null field
POST {{URI}}/objects/bird HTTP/1.1
content-type: application/json

{
"attrs": {
    "color": "orange",
    "specie": "bird with null field (field absent of the request)"
}
}

###

# CREATE => with field of null value
POST {{URI}}/objects/bird HTTP/1.1
content-type: application/json

{
"attrs": {
    "color": "orange",
    "specie": "bird with null field",
    "height": null
}
}

###

# SHOULD FAIl
# CREATE => missing an non nullable field
POST {{URI}}/objects/bird HTTP/1.1
content-type: application/json

{
    "attrs": {
        "specie": "Should not endup in database"
    }
}

###

# SHOULD FAIl
# CREATE => sending a null value non a non nullable field
POST {{URI}}/objects/bird HTTP/1.1
content-type: application/json

{
    "attrs": {
        "color": null,
        "specie": "Should not endup in database"
    }
}

###

# UPDATE a bird
PUT {{URI}}/objects/bird/{{birdid}} HTTP/1.1
content-type: application/json

{
    "attrs": {
        "color": "red",
        "specie": "rouge gorge",
        "height": null,
        "weight": 8.55
    }
}